# Generated by Django 2.1.3 on 2018-11-26 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20181123_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
